### ISSUE TITLE
Q35, option (d) Security vs Legal compliance, wrong answer

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#127]
Option (d) is highly disputable, as rogue nations might have laws that diminish information security
(e.g. the US NSA has the legal rights to access private information from companies like Amazon or Google,
clearly violating privacy and reducing personal information security.

Therefore option d can be in conflict

**Comment by alxlo** [comment]
Full ACK. Legal interception interfaces and government back doors are my go-to example for arguing that this answer is highly disputable. There are literally dozens of examples out there that this has been and is continuing to be exploited.

**Comment by feststelltaste** [comment]
I see the points and I totally agree. 

The question is
> Which of the following pairs of qualities are usually in conflict to each other, and which are not?

The mean word is "usually", because backdoors are not the daily business of everyone. So, the answer could work, but the rationale is not very convincing.

But to improve the question, see PR #129, which replaces "compliance" with "functional correctness", because you can usually have both qualities addressed simultaneously in your software system.

**Comment by alxlo** [comment]
This is fixed with merge of PR #129, we will still have to release a new version but the issue can be closed.
