### ISSUE TITLE
check compliance of mock exam with upcoming curriculum

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#60]
I have the gut feeling that several questions refer to learning goals that are R3...

**Comment by rhoadesre** [comment]
I think this is completely fine. The mock exams are there to give the students a feeling about the difficulty level of the questions and how the questions are formulated. It might be a good thing that the questions cover R3 topics so that we don't have to constantly think of similar, but different questions for the R1 and R2 topics.

**Comment by gernotstarke** [comment]
ok, let's close this
